name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-then-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
              docker build . --tag ghcr.io/ArianFotouhi/store:latest
              docker push ghcr.io/ArianFotouhi/store:latest
