name: Build & Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Push the Docker image
      run: |
        echo "${{secrets.DOCKER_HUB_PASSWORD}}" | docker login -u "${{secrets.DOCKER_HUB_USERNAME}}" --password-stdin
        docker image build -t arianfotouhi/classfierapi:v1  .
        docker push arianfotouhi/classfierapi:v1
